### ISSUE TITLE
[BUG] Flutter chopper generator converts body parameters from snake_case into camelCase 

### ISSUE THREAD

**Issue by mekonnen070** [epam-cross-platform-lab/swagger-dart-code-generator#532] opened 2023-01-08 16:58 UTC
The package works awesome for get requests, however when I try to do post requests things break. The backend goes like: parameters are missing... While it expects multipart form, with snake_case parameters:
```dart 
profile_name
profile_tag
```
So I looked into and
Here is what gets generated:
```dart
@override
  Future<Response<MyProfileSchema>> _apiCreateProfilePost({
    required String? profileName,
    required String? profileTag,
  }) {
    final Uri $url = Uri.parse('/api/create/profile/');
    final List<PartValue> $parts = <PartValue>[
      PartValue<String?>(
        'profileName',      <<<
        profileName,
      ),
      PartValue<String?>(
        'profileTag',          <<<
        profileTag,
      ),
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<MyProfileSchema, MyProfileSchema>($request);
  }
```
This is what should be generated:

```dart
  @override
  Future<Response<MyProfileSchema>> _apiCreateProfilePost({
    required String? profileName,
    required String? profileTag,
  }) {
    final Uri $url = Uri.parse('/api/create/profile/');
    final List<PartValue> $parts = <PartValue>[
      PartValue<String?>(
        'profile_name',       <<<
        profileName,
      ),
      PartValue<String?>(
        'profile_tag',          <<<
        profileTag,
      ),
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<MyProfileSchema, MyProfileSchema>($request);
  }
```
openapi.json has every value in the snake case.
We are using:
```dart 
dev_dependencies:
  build_runner: ^2.3.2
  chopper_generator: ^6.0.0
  flutter_native_splash: ^2.2.8
  json_serializable: ^6.5.4
  swagger_dart_code_generator: ^2.8.9
```
is there any way we could make it so that generated code does not convert snake_case into camelCase?

**Comment by techouse** [comment] 2023-01-09 08:48
The authors of Swagger Dart Generator will have to adjust their code to use the `name` parameters of `@Part` annotations as explained here https://github.com/lejard-h/chopper/issues/401#issuecomment-1374800965

Going forward [Chopper](https://github.com/lejard-h/chopper) should probably start supporting the use of a global builder configuration, [just like `json_serializable` does](https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration).

**Comment by Vovanella95** [comment] 2023-01-20 07:38
Hi @techouse , could you please provide example of swagger file should be snake cased?

**Comment by Vovanella95** [comment] 2023-01-23 17:25
Duplicate of #531

**Closed by Vovanella95** 2023-01-23 17:25 UTC
Labels: bug, Triage needed
