### ISSUE TITLE
[BUG] Re-generating the dart code from swagger removed mappings

### ISSUE THREAD

**Issue by iresharma-triomics** [epam-cross-platform-lab/swagger-dart-code-generator#471] opened 2022-10-05 10:28 UTC
We just re-generated our dart code from a new swagger, it removed a lot of code that specifically added fromJsonFactories to the `generatedMapping` dictionary.

**To Reproduce**
We are not really sure why the generator randomly deleted these lines.

**Swagger specification link**
Private API swagger.

**Library version used:**
our pubspec specifies version number as null so we're using the latest version.

**Additional context**
I'd like to tag my teammate for us to in loop @ankit-triomics

![Screenshot 2022-10-05 at 3 57 29 PM](https://user-images.githubusercontent.com/112384697/194039606-27fa9011-ef6b-4ebb-b39b-b662025f3b4e.png)

**Comment by Vovanella95** [comment] 2022-10-11 09:59
Hi @iresharma-triomics 

I'm on business trip next 2 weeks. Will handle all tickets asap when return home :)

**Comment by ankit-triomics** [comment] 2022-10-12 09:57
thanks for letting us know, @Vovanella95. :)

**Comment by Vovanella95** [comment] 2022-11-01 07:05
Hi @ankit-triomics  this issue is not reproduced on my side. Possible you're using latest version of generator and it works differently. Could you please share your swagger file to make sure issue is reproduced?

Also could you please check is bug reproduced on latest version of generator?

**Comment by Vovanella95** [comment] 2022-11-17 07:41
@ankit-triomics closing the issue due to no answer. Please reopen it if issue is still actual

**Closed by Vovanella95** 2022-11-17 07:41 UTC
Labels: bug, Triage needed
