### ISSUE TITLE
[BUG] required keyword not generated for named parameters

### ISSUE THREAD

**Issue by davorzlotrg** [epam-cross-platform-lab/swagger-dart-code-generator#451] opened 2022-08-24 10:01 UTC
Following json

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "Api",
    "version": "v1"
  },
  "paths": {
	"/api/companies/company": {
      "post": {
        "tags": [
          "Companies"
        ],
        "parameters": [
          {
            "name": "LANGUAGE",
            "in": "header",
            "description": "Controls the language the API uses"
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "Id": {
                    "type": "integer",
                    "format": "int32"
                  },
                  "Name": {
                    "type": "string"
                  }
                }
              },
              "encoding": {
                "Id": {
                  "style": "form"
                },
                "Name": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  }
}
```

Generates the following code 

```
  ///
  ///@param LANGUAGE Controls the language the API uses
  Future<chopper.Response> apiCompaniesCompanyPost(
      {String? language,
      int Id,
      String Name}) {
    return _apiCompaniesCompanyPost(
        language: language,
        Id: Id,
        Name: Name);
  }

  ///
  ///@param LANGUAGE Controls the language the API uses
  @Post(path: '/api/companies/company')
  @Multipart()
  Future<chopper.Response> _apiCompaniesCompanyPost(
      {@Header('LANGUAGE') String? language,
      @Part() int Id,
      @Part() String Name});
```

It is giving compile error because in this case the parameter 'Id' can't have a value of 'null' because of its type, but the implicit default value is 'null'. It should be required int Id and required String Name. 

Also is there a way that property names are generated as lowerCamelCase?

**Comment by Vovanella95** [comment] 2022-09-15 15:09
Hi @davorzlotrg!
Looking into it

**Comment by Vovanella95** [comment] 2022-09-20 11:13
Hi @davorzlotrg 
I've generated your code.
required keyword is not generated, because these parameters does not have `required` keyword, so, potentially, they can be null.  So, it's not a bug. Please make sure it's not null in your code.

About loserCamelCase. In latest version I have next generated code:
```dart
///
  ///@param LANGUAGE Controls the language the API uses
  Future<chopper.Response> apiCompaniesCompanyPost(
      {String? language, String? cacheControl, int? id, String? name}) {
    return _apiCompaniesCompanyPost(
        language: language, cacheControl: cacheControl, id: id, name: name);
  }

  ///
  ///@param LANGUAGE Controls the language the API uses
  @Post(path: '/api/companies/company')
  Future<chopper.Response> _apiCompaniesCompanyPost(
      {@Header('LANGUAGE') String? language,
      @Header('Cache-Control') String? cacheControl,
      @Part() int? id,
      @Part() String? name});
```

Looks like name is fine.
Closing the issue.

**Closed** 2022-09-20 11:14 UTC
Labels: bug, Triage needed
