### ISSUE TITLE
Issue with generation in Response<Bool> while code generation

### ISSUE THREAD

**Issue by sakthivel-sm** [epam-cross-platform-lab/swagger-dart-code-generator#142] opened 2021-03-15 13:14 UTC
Thanks for this very useful library. Appreciate the hard work.

As described in https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/58 - we still face the issue where the return type is generated as 
` Future<Response<Bool>> ` instead of ` Future<Response<bool>> ` causing compile time errors.

Having gone through the changes in https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/60 it didn't look like `bool` was included in the list of exception words.

We are currently using `swagger_dart_code_generator: ^1.6.8` and still seeing the issue.

Requesting for any advice or assistance.

**Comment by fryette** [comment] 2021-03-17 11:41
is it possible to share the swagger file to reproduce the issue?

**Comment by sakthivel-sm** [comment] 2021-03-17 13:59
Hey @fryette, Here's the link `https://devweb.optotax.com/optomoney/v3/api-docs`.

**Comment by syq7970** [comment] 2021-04-12 05:12
I havan same issue. Swagger json file generic type with '«»' will break generation with Illegal character error message.

**Comment by fryette** [comment] 2021-04-12 09:04
Now we are mostly working on the null-safety version.

We will take a look at it this week.

@syq7970 Swagger has standards and if it breaks standards we really don't want to support it because it is impossible to handle all issues. 

As a workaround, you can write a script that will remove all illegal characters from your swagger files and then run generation.

**Comment by syq7970** [comment] 2021-04-12 09:13
@fryette 
Thx for reply.
I'm trying fix illegal characters with script, but it seems like the generation process is not completed, because illegal characters break the process, so even replace all  '«»' to '<>', It still have lot of errors.
Maybe it is dart not support 'illegal characters', I use Swift code generation  with the same Api json file, and it worked like a charm.

**Comment by fryette** [comment] 2021-04-12 13:08
@syq7970 is it possible to create the separate issue and share swagger?

**Comment by LanderTome** [comment] 2021-07-21 06:14
I have run into the same Response<Bool> issue as @sakthivel-sm. I believe that the issue is at line 426 of the src/code_generators/swagger_requests_generator.dart file.

`     if (returnType.isNotEmpty && returnType != 'num') {
      returnType = returnType.pascalCase;
    }
`

When the returnType 'bool' comes along, it Pascal cases it to 'Bool'. It works as expected if I modify the line to:

`    
    if (returnType.isNotEmpty && (returnType != 'num' && returnType != 'bool')) {
      returnType = returnType.pascalCase;
    }
`

Not sure, but might this affect other built-in types?

**Comment by Vovanella95** [comment] 2021-07-21 08:43
Hi @LanderTome ,

if you want feel free to create PR with fix. Or I can take a look into it soon.

**Comment by Vovanella95** [comment] 2021-08-28 14:24
Hi @sakthivel-sm , @syq7970 , @LanderTome , 

Just checked your file and it's generated without issues. Thanks @LanderTome  for fix. I'm closing the issue. Feel free to create another ones :)

**Closed by Vovanella95** 2021-08-28 14:24 UTC

**Comment by Vovanella95** [comment] 2021-08-28 14:27
The only one thing there is no next ref

`Error-ModelName{namespace='org.javers.core.diff', name='Change'}`

It's crazy thing possible swagger file is incorrect :D
